# Numpy Exercise Solutions

### Exercise 1
Import Numpy. Create a numpy array called Array_A that includes the following values: a three dimensional array with these values [1,2,3,4], [5,6,7,8], and [9,10,11,12]. Print the array and print the third item in the second row of the array.

In [1]:
import numpy as np

Array_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (Array_A)
print (Array_A [1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


### Exercise 2 
Print the shape of Array_A, and reshape it to be 6 columns and 2 rows.

In [ ]:
Array_A.shape

(3, 4)

In [ ]:
Array_A.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Exercise 3 
Create Array_B with 5 rows and 3 columns. The values in the array are integers ranging from -75 to 75. Print the whole array. Then check the values in the array and see which ones are above 0.

In [ ]:
Array_B = np.random.randint(-75,75,(5,3))
print(Array_B)
print(Array_B>0)

[[ 44 -40 -27]
 [ 14  66  34]
 [-37 -18 -47]
 [-15  66  17]
 [ -9  25  25]]
[[ True False False]
 [ True  True  True]
 [False False False]
 [False  True  True]
 [False  True  True]]


### Exercise 4
Create Array_C with 4 random floats. Use the seed function to make sure you get the same values everytime you run the code. Print the whole array, and then print the values that are above or equal to 0.5.

In [ ]:
np.random.seed(10)
Array_C = np.random.rand(4)
print(Array_C)
print(Array_C[Array_C>=0.5])

[0.77132064 0.02075195 0.63364823 0.74880388]
[0.77132064 0.63364823 0.74880388]
